### ISSUE TITLE
addon not compatible with atom 1.2.0?

### ISSUE THREAD

**Issue by sluedecke** [griffin-stewie/asciidoctor-preview#11]
Rebuilding on atom 1.2.0 fails with the error below.

Is this a compatibility issue or just my wrongdoing?

```
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../node_modules/nan/nan.h:260:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:255:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:660:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:660:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:664:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:664:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:671:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/saschal/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:41:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/saschal/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:41:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../node_modules/nan/nan.h:671:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/saschal/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:53:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/saschal/.atom/.node-gyp/.node-gyp/0.34.0/src/node_buffer.h:53:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../node_modules/nan/nan.h:671:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:675:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.0-18-lowlatency
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/saschal/.atom/packages/asciidoctor-preview/node_modules/pathwatcher
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Linux 4.2.0-18-lowlatency
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/saschal/.atom/.apm/.apmrc" "--userconfig" "/home/saschal/.atom/.apmrc" "rebuild" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! pathwatcher@4.4.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@4.4.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pathwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pathwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saschal/.atom/packages/asciidoctor-preview/npm-debug.log

```

**Comment by randybb** [comment]
I have the same problem.

**Comment by griffin-stewie** [comment]
I'm going to fix it soon.

**Comment by griffin-stewie** [comment]
@sluedecke @randybb 
I released v0.1.6 for Atom 1.2.0.

**Comment by sluedecke** [comment]
Great, thanks a lot for making it work again!

Unfortunately now it fails for me.  It tries to call:

```
Command failed: /bin/sh -c asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram -o /tmp/asciidoctor1151028-6532-d3vznr/temp.html /tmp/asciidoctor1151028-6532-d3vznr/diary-2015-11.adoc /usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'asciidoctor' (>= 0) among 9 total gem(s) (Gem::LoadError) Checked in 'GEM_PATH=/.gem/ruby/2.2.0:/usr/lib/ruby/gems/2.2.0', execute `gem env` for more information from /usr/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec' from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem' 
```

I can make it work when I surround the command with "" like:

```
/bin/sh -c "asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram -o /tmp/asciidoctor1151028-6532-d3vznr/temp.html /tmp/asciidoctor1151028-6532-d3vznr/diary-2015-11.adoc"
```

I am running arch linux and my bash is 4.3.42 which is the binary behind /bin/sh as well.

**Comment by sluedecke** [comment]
Giving it some thoughs and a closer look, it turns out that you strip down the environment for the asciidoctor call to include only the PATH component.  This happens in renderer.coffee around line 58: 

`@exec command, {"env": {"PATH": pathForCommands}}, (error, stdout, stderr) =>`

but the ruby gem mechanism needs a HOME variable to be set (I have installed the asciidoctor gem in my personal profile), and it works once I change the line to:

`@exec command, {"env": {"HOME": process.env.HOME, "PATH": pathForCommands}}, (error, stdout, stderr) =>`

HTH (PS: running on atom 1.2.4)

**Comment by griffin-stewie** [comment]
@sluedecke 

Thank you, your help.
Actually I'm not good at `ENV`, `PATH` and `gem` stuff like that "UNIX" things.

However I'm going to fix it.

**Comment by griffin-stewie** [comment]
@sluedecke
I released v0.1.7. Can you check try it?

**Comment by sluedecke** [comment]
Works like a charm with atom 1.2.4 on ArchLinux (can be closed from my perspective)

**Comment by griffin-stewie** [comment]
:+1:
