### ISSUE TITLE
Uncaught Error: Cannot find module '../build/Release/pathwatcher.node'

### ISSUE THREAD

**Issue by yong1236** [griffin-stewie/asciidoctor-preview#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Unknown Windows Version
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.1.7
### Stack Trace

Uncaught Error: Cannot find module '../build/Release/pathwatcher.node'

```
At module.js:338

Error: Cannot find module '../build/Release/pathwatcher.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Tony\.atom\packages\asciidoctor-preview\node_modules\pathwatcher\lib\main.js:6:13)
    at Object.<anonymous> (C:\Users\Tony\.atom\packages\asciidoctor-preview\node_modules\pathwatcher\lib\main.js:207:4)
    at Module._compile (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Tony/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:8:10)
    at Object.<anonymous> (file:///C:/Users/Tony/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:1:1)
    at Module._compile (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at isAsciidoctorPreviewView (file:///C:/Users/Tony/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:14:29)
    at Object.module.exports.toggle (file:///C:/Users/Tony/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:78:8)
    at atom-workspace.atom.commands.add.asciidoctor-preview:toggle (file:///C:/Users/Tony/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:55:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Tony\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -0:03.5.0 asciidoctor-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
asciidoc-preview, v0.6.0
asciidoctor-preview, v0.1.7
AtomicChar, v0.3.11
language-asciidoc, v0.12.0

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@yong1236 
I'm sorry that I cannot reproduce this issue because I don't have Windows.
