### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/highlights'

### ISSUE THREAD

**Issue by PaulAnderson-One** [griffin-stewie/asciidoctor-preview#24]
[Enter steps to reproduce below:]
1. preview a file
2. see the bug

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.3.0
### Stack Trace

Uncaught Error: Cannot find module '/Users/paul.anderson/.atom/packages/highlights'

```
At module.js:340

Error: Cannot find module '/Users/paul.anderson/.atom/packages/highlights'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/renderer.coffee:14:14)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/renderer.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:6:25)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at isAsciidoctorPreviewView (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:14:29)
    at Object.module.exports.toggle (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:78:8)
    at atom-workspace.atom.commands.add.asciidoctor-preview:toggle (/Users/paul.anderson/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:55:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:30.9.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:26.8.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:cancel (a.stack-toggle)
     -0:00.7.0 asciidoctor-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "minimap"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pdf"
    ]
  },
  "asciidoctor-preview": {
    "command": "asciidoctor --trace --safe-mode unsafe -a lang=en -b html5 -d book  --base-dir {{{baseDirPath}}} -o {{{tempHTMLPath}}} {{{filePath}}}",
    "renderOnSaveOnly": true
  }
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.31
asciidoc-preview, v2.4.2
asciidoctor-preview, v0.3.0
language-asciidoc, v1.5.1
linter, v1.11.10
markdown-preview, v0.158.0
pandoc-convert, v1.0.4
pigments, v0.29.2
red-wavy-underline, v0.3.0
revealjs-preview, v0.3.1

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@PaulAndersonMule 
Could you try install atom to `/Applications/` ?
