### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by bornio** [griffin-stewie/asciidoctor-preview#25]
Trying a simple preview of the following string:

```
[[app-listing]]
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
```

**Atom Version**: 1.9.9
**System**: Mac OS X 10.12
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.3.0
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1188:7)
    at Object.copy (/Users/zzz/.atom/packages/asciidoctor-preview/node_modules/fs-extra/lib/copy/copy.js:18:26)
    at /Users/zzz/.atom/packages/asciidoctor-preview/lib/renderer.coffee:54:10
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/scandal/node_modules/temp/lib/temp.js:231:7
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -1:38.7.0 core:select-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:37.8.0 core:cut (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -1:37 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -1:33.8.0 editor:log-cursor-scope (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:28.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:53.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.5.0 asciidoctor-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode)
     -0:06.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 asciidoctor-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode)
     -0:02.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 asciidoctor-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "asciidoc-preview"
    ],
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  },
  "asciidoctor-preview": {}
}
```
### Installed Packages

``` coffee
# User
aligner-python, v1.0.1 (active)
asciidoc-assistant, v0.2.1 (active)
asciidoc-image-helper, v1.0.0 (active)
asciidoc-preview, v2.6.0 (inactive)
asciidoctor-preview, v0.3.0 (active)
atom-beautify, vundefined (active)
autocomplete-asciidoc, v0.1.1 (active)
autocomplete-python, v1.8.6 (active)
language-asciidoc, v1.5.1 (active)
language-confluence-wiki, v0.2.0 (active)
language-docker, v1.1.7 (active)
language-nginx, v0.6.1 (active)
language-scala, v1.1.6 (active)
linter, v1.11.16 (active)
linter-scalac, v1.4.2 (active)
markdown-format, v2.5.1 (active)
markdown-table-formatter, v2.8.3 (active)
markdown-writer, v2.5.1 (active)
merge-conflicts, v1.4.4 (active)
pretty-json, v1.6.0 (active)
python-tools, v0.6.8 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@bornio 
I could not reproduce this issue.

Atom Version: 1.10.2
System: Mac OS X 10.12
Thrown From: asciidoctor-preview package, v0.3.1

**Comment by natgau** [comment]
When I try to start the asciidoc-preview from Atom, I also get the error message mentioned by bornio:

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Object.copy (C:\Users\ngauthie.atom\packages\asciidoctor-preview\node_modules\fs-extra\lib\copy\copy.js:18:26)
    at file:///C:/Users/ngauthie/.atom/packages/asciidoctor-preview/lib/renderer.coffee:54:10
    at C:\Users\ngauthie.atom\packages\asciidoctor-preview\node_modules\temp\lib\temp.js:231:7
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by natgau** [comment]
Earlier today, I ran the following command:
apm install asciidoctor-preview

Just now, I ran the command again.

In Atom under Packages, there are now two menu items:
AsciiDoc Preview
asciidoctor-preview

The first one (AsciiDoc Preview) works, the second one (asciidoctor-preview) does not.

**Comment by natgau** [comment]
Here is another update. I have just realized that I did not use the same command twice. The commands are similar but not the same. 

So, here is a summary:

The apm install asciidoctor-preview command installs a package that does not start.

Use the following command:
apm install asciidoc-preview

**Comment by griffin-stewie** [comment]
@bornio @natgau 

Could you make sure following list?
- Install [Asciidoctor](http://asciidoctor.org/#installation) on your $PATH
- adoc document must be saved on disk.

`asciidoctor-preview` (my atom package. not asciidoc-preview) works under the hood,
1. Using asciidoctor command to convert adoc text to html
   - You can see settings "command" like this `asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir {{{baseDirPath}}} -o {{{tempHTMLPath}}} {{{filePath}}}`
2. Move converted html document to temp directory 
3. Open the converted html on the Preview Pane
