### ISSUE TITLE
Previewing AsciiDoc Failed

### ISSUE THREAD

**Issue by ali-gs** [griffin-stewie/asciidoctor-preview#26]
Atom is not able to preview the asciidoc file 

**The viewer shows below**

Command failed: asciidoctor --safe-mode unsafe -a lang=ja -b html5 -d book -r asciidoctor-diagram --base-dir E:\ztemp -o C:~\AppData\Local\Temp\asciidoctor11688-11556-h9jrwa.e0lv75vcxr\temp.html E:\ztemp\p.adoc 'asciidoctor' is not recognized as an internal or external command, operable program or batch file.

**Got a popup as below**

Unexpected token  in C:~.atom\packages\asciidoc-preview\package.json
Hide Stack Trace
SyntaxError: Unexpected token 
    at Object.parse (native)
    at parseObject (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.module.exports.readFileSync (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\season\lib\cson.js:170:14)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:700:29)
    at PackageManager.module.exports.PackageManager.loadPackage (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:423:36)
    at C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:397:19)
    at C:~\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:749:28
  at C:~.atom\packages\asciidoc-preview\package.json:1:1

**Comment by ali-gs** [comment]
fixed the issue by changing the "path" in settings to C:\Ruby22\bin

but still the diagrams are not rendered and see below error

Failed to generate image: No such file or directory - reg query "HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft" /s /v JavaHome

**Comment by griffin-stewie** [comment]
@ali-gs 
Did you install `asciidoctor/asciidoctor-diagram` ?
Maybe you should make sure your PATH and gem pathes.
I don't know about Ruby stuffs, and Windows. I am sorry.

**Comment by ali-gs** [comment]
Yes I had it all installed already.
I fixed it by 

Command:
asciidoctor --safe-mode unsafe -a lang=en -b html5 -d book -r asciidoctor-diagram --base-dir {{{baseDirPath}}} -o {{{tempHTMLPath}}} {{{filePath}}}

PATH:
C:\Ruby22\bin

**Comment by ali-gs** [comment]
I had fixed the Ruby path but still the diagrams are not rendered and see below error

Failed to generate image: No such file or directory - reg query "HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft" /s /v JavaHome

So reopen this issue

**Comment by griffin-stewie** [comment]
@ali-gs 
I don't know about Ruby & Java stuffs, and Windows. I am sorry.
