### ISSUE TITLE
Uncaught Error: Unclosed tag at 149

### ISSUE THREAD

**Issue by k-matsunuma** [griffin-stewie/asciidoctor-preview#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package 0.3.2

### Stack Trace

Uncaught Error: Unclosed tag at 149

```
At C:\Users\k-matsunuma\.atom\packages\asciidoctor-preview\node_modules\mustache\mustache.js:198

Error: Unclosed tag at 149
    at parseTemplate (/packages/asciidoctor-preview/node_modules/mustache/mustache.js:198:15)
    at Writer.parse (/packages/asciidoctor-preview/node_modules/mustache/mustache.js:450:34)
    at Writer.render (/packages/asciidoctor-preview/node_modules/mustache/mustache.js:465:23)
    at Object.render (/packages/asciidoctor-preview/node_modules/mustache/mustache.js:603:26)
    at /packages/asciidoctor-preview/lib/renderer.coffee:63:22
    at /packages/asciidoctor-preview/lib/renderer.coffee:57:7
    at doneOne (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/fs-extra/lib/copy/ncp.js:228:16)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/fs-extra/lib/copy/ncp.js:121:11
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/graceful-fs/polyfills.js:239:18
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
  2x -8:03.2.0 core:move-up (input.hidden-input)
     -7:57.3.0 editor:newline (input.hidden-input)
     -7:55.9.0 core:save (input.hidden-input)
     -7:37.6.0 core:move-up (input.hidden-input)
     -7:37.1.0 editor:newline (input.hidden-input)
  2x -7:33.2.0 core:backspace (input.hidden-input)
     -7:28.6.0 core:page-up (input.hidden-input)
  5x -7:27.6.0 core:backspace (input.hidden-input)
     -7:17.3.0 editor:newline (input.hidden-input)
  5x -7:09.7.0 core:backspace (input.hidden-input)
 10x -7:01.4.0 core:move-left (input.hidden-input)
     -6:58.6.0 core:save (input.hidden-input)
     -0:24.3.0 core:move-left (input.hidden-input)
  3x -0:23 core:move-right (input.hidden-input)
     -0:20.9.0 core:save (input.hidden-input)
     -0:17.3.0 asciidoctor-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.3 
asciidoctor-preview 0.3.2 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.11.0 
language-markdown 0.25.1 
language-plantuml 0.2.0 
markdown-preview-plus 2.4.16 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
plantuml-viewer 0.7.2 
tablr 1.8.3 
```

**Comment by griffin-stewie** [comment]
I am sorry but I can only support macOS.
