### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by kaanpakpum** [griffin-stewie/asciidoctor-preview#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.200.0
**System**: linux 4.1.0-040100rc2-lowlatency
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.1.5
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:819

TypeError: path must be a string
  at TypeError (native)
  at fs.lstat (fs.js:819:11)
  at Object.fs.lstat (ATOM_SHELL_ASAR.js:187:16)
  at Object.copy (/home/kk/.atom/packages/asciidoctor-preview/node_modules/fs-extra/lib/copy.js:39:6)
  at /home/kk/.atom/packages/asciidoctor-preview/lib/renderer.coffee:37:10
  at /opt/atom/resources/app.asar/node_modules/temp/lib/temp.js:231:7
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
     -4:19.4.0 core:paste (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -4:02.3.0 editor:newline (atom-text-editor.editor.insert-mode.vim-mode.is-focused)
     -3:47.3.0 core:page-down (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
     -3:46.9.0 core:page-up (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
  2x -3:46.5.0 core:move-up (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
     -3:45.7.0 core:move-down (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
  3x -3:45.4.0 core:move-right (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
 14x -3:41.8.0 core:backspace (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
  2x -2:11.9.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -2:02.8.0 core:backspace (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
  2x -1:30.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 10x -1:07.3.0 core:backspace (atom-text-editor#editor.lineHeight.editor.mini.is-focused)
  2x -0:38.6.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -0:25.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:20.9.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:03.6.0 asciidoctor-preview:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ascii-codes, v0.3.3
asciidoc-preview, v0.5.0
asciidoctor-preview, v0.1.5
crosshairs, v0.1.2
default-language, v0.1.2
documentation-renderer, v0.2.0
language-RSL, v0.31.0
language-asciidoc, v0.11.1
language-context-free, v0.8.0
language-gherkin-i18n, v1.1.2
language-glsl, v2.0.0
language-opencl, v0.1.1
language-vex, v0.1.3
language-xtend, v0.4.0
less-than-slash, v0.6.0
minimap, v4.9.0
vim-mode, v0.48.0

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@kaanpakpum 
Can you try to do with latest Atom and asciidoctor-preview package ?
