### ISSUE TITLE
Uncaught Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/highlights'

### ISSUE THREAD

**Issue by m9tz** [griffin-stewie/asciidoctor-preview#44]
[Enter steps to reproduce:]

1. adding a new projectfolder
2. create a file out of atom with "a" name test1.adoc
3. type a h1 and h2 content
4. try to preview
5. fails

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Debian GNU/Linux
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package 0.3.2

### Stack Trace

Uncaught Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/highlights'

```
At module.js:545

Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/highlights'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/asciidoctor-preview/lib/renderer.coffee:14:14)
    at /packages/asciidoctor-preview/lib/renderer.coffee:1:1)
    at /packages/asciidoctor-preview/lib/renderer.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:6:25)
    at /packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:1:1)
    at /packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at isAsciidoctorPreviewView (/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:14:29)
    at Object.toggle (/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:78:8)
    at /packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:55:41)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:669183)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:676567)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:54.3.0 application:add-project-folder (div.tool-panel.tree-view)
     -1:40.4.0 tree-view:add-file (div.tool-panel.tree-view)
     -1:31.8.0 core:confirm (input.hidden-input)
  4x -1:16.7.0 editor:newline (input.hidden-input)
     -0:41 asciidoctor-preview:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
asciidoc-preview undefined 
asciidoctor-preview 0.3.2 
atom-browser 0.70.0 
atom-clock 0.1.16 
atom-formatter-jsbeautify 1.1.2 
atom-js-console 1.2.2 
atom-latex 0.8.5 
atom-terminal 0.8.0 
atomic-emacs 0.13.0 
browser-plus 0.0.98 
css-snippets 1.1.0 
file-icons 2.1.29 
git-plus 8.4.2 
go-plus 6.1.0 
hidpi 0.14.0 
Hydrogen 2.7.0 
javascript-snippets 1.2.1 
language-hugo 0.5.1 
language-latex 1.2.0 
language-openscad 0.4.3 
language-svg 0.9.2 
languagetool 0.1.1 
latex 0.50.2 
latex-completions 0.3.6 
man 0.8.2 
markdown-preview-plus 3.7.1 
org-mode 0.3.16 
pandoc-convert 1.1.1 
pdf-view 0.71.0 
platformio-ide-terminal 2.9.0 
project-manager 3.3.6 
rename-tabs 0.2.0 
sass 0.5.0 
svg-icons 0.5.3 
svg-preview 0.14.0 
svgo 3.2.0 
teletype 0.13.3 
terminal-plus 0.14.5 
tree-view-git-status 1.5.2 
```

**Comment by m9tz** [comment]
old
