### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by purplepalmdash** [griffin-stewie/asciidoctor-preview#47]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.12
**OS**: "Arch Linux"
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package 0.3.2

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at Object.copy (/packages/asciidoctor-preview/node_modules/fs-extra/lib/copy/copy.js:26:28)
    at /packages/asciidoctor-preview/lib/renderer.coffee:54:10
    at /usr/lib/atom/node_modules/archive-view/node_modules/temp/lib/temp.js:231:7
    at FSReqWrap.oncomplete (fs.js:141:20)
```

### Commands

```
 23x -1:15.3.0 core:backspace (input.hidden-input)
     -1:10.1.0 core:paste (input.hidden-input)
     -0:34.6.0 asciidoctor-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
asciidoctor-preview 0.3.2 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.11.0 
```

**Comment by purplepalmdash** [comment]
Could not preview un-saved documents. After `save as` the preview works well.
