### ISSUE TITLE
Uncaught Error: Cannot find module '/usr/share/atom/resources/app/node_modules/highlights'

### ISSUE THREAD

**Issue by AVGP** [griffin-stewie/asciidoctor-preview#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.174.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.1.5
### Stack Trace

Uncaught Error: Cannot find module '/usr/share/atom/resources/app/node_modules/highlights'

```
At module.js:346

Error: Cannot find module '/usr/share/atom/resources/app/node_modules/highlights'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/martin/.atom/packages/asciidoctor-preview/lib/renderer.coffee:14:14)
  at Object.<anonymous> (/home/martin/.atom/packages/asciidoctor-preview/lib/renderer.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/martin/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:10:12)
  at Object.<anonymous> (/home/martin/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at isAsciidoctorPreviewView (/home/martin/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:14:29)
  at Object.module.exports.toggle (/home/martin/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:78:8)
  at atom-workspace.atom.commands.add.asciidoctor-preview:toggle (/home/martin/.atom/packages/asciidoctor-preview/lib/asciidoctor-preview.coffee:55:41)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```
### Commands

```
     -7:59.0 core:save (atom-text-editor.editor)
 11x -7:33.2 core:backspace (atom-text-editor.editor)
     -7:30.7 core:save (atom-text-editor.editor)
     -1:23.7 asciidoctor-preview:toggle (atom-text-editor.editor)
     -1:14.4 asciidoc-preview:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -1:11.8 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:20.8 core:undo (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:20.1 core:select-all (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:19.9 core:backspace (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:18.6 core:move-right (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:18.2 core:move-down (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:17.8 core:move-left (atom-text-editor#asciidoctor-preview.command.editor.mini)
  2x -0:12.8 core:backspace (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:10.4 core:save (atom-text-editor#asciidoctor-preview.command.editor.mini)
     -0:07.2 application:open-folder (atom-text-editor.editor)
  2x -0:00.0 asciidoctor-preview:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  },
  "asciidoctor-preview": {
    "command": "asciidoctor -d book",
    "renderOnSaveOnly": true
  }
}
```
### Installed Packages

``` coffee
# User
asciidoc-preview, v0.5.1
asciidoctor-preview, v0.1.5
autocomplete-css, v0.7.2
autocomplete-html, v0.7.2
autocomplete-modules, v0.3.5
autocomplete-paths, v1.0.2
language-asciidoc, v0.11.1
language-rust, v0.4.3
language-scala, v1.1.3
linter, v0.12.7
linter-jshint, v0.1.6

# Dev
No dev packages
```

/cc @atom/core

When I ran into this, I noticed that it goes resolves the path to `markdown-preview` but then goes into the parent directory instead of traversing into `markdown-preview/node_modules`.

So I did a small change in https://github.com/griffin-stewie/asciidoctor-preview/blob/b4d6143f23ada6d77dfb706d798e0c6e8b9abb8d/lib/renderer.coffee#L14:

``` coffeescript
Highlights = require path.join(pathWatcherDirectory, 'node_modules', 'highlights')
```

 and it works. Is that something that magically only happened on my system or a general bug?

**Comment by griffin-stewie** [comment]
@AVGP 
Your Atom is too old anyway. asciidoctor-preview is supporting from 0.189.0.

**Comment by AVGP** [comment]
Indeed - an update fixed the issue. :)

**Comment by griffin-stewie** [comment]
:)
