### ISSUE TITLE
Uncaught Error: Cannot find module '/Users/stepup/.atom/packages/highlights'

### ISSUE THREAD

**Issue by boggle** [griffin-stewie/asciidoctor-preview#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [asciidoctor-preview](https://github.com/griffin-stewie/asciidoctor-preview) package, v0.1.5
### Stack Trace

Uncaught Error: Cannot find module '/Users/stepup/.atom/packages/highlights'

```
At module.js:336

Error: Cannot find module '/Users/stepup/.atom/packages/highlights'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoctor-preview/lib/renderer.coffee:26:16)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoctor-preview/lib/renderer.coffee:201:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Commands

```
     -0:01.1.0 asciidoctor-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/stepup/Source",
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false
  },
  "asciidoctor-preview": {
    "renderOnSaveOnly": true,
    "path": "/Users/stepup/.rvm/gems/ruby-2.1.5/bin/asciidoctor",
    "command": "asciidoctor --safe-mode unsafe -a lang=en -b html5 -d book -r asciidoctor-diagram -o {{{tempHTMLPath}}} {{{tempSourcePath}}}"
  }
}
```
### Installed Packages

``` coffee
# User
asciidoctor-preview, v0.1.5
autocomplete-haskell, v0.5.1
bracket-matcher, v0.77.0
emmet, v2.3.12
haskell-ghc-mod, v0.9.10
ide-haskell, v0.7.2
imdone-atom, v1.1.38
language-asciidoc, v0.12.0
language-cypher, v0.3.0
language-haskell, v1.4.6
language-java, v0.16.0
language-rust, v0.4.5
language-scala, v1.1.3
linter, v1.6.0
linter-hlint, v0.4.2
markdown-preview, v0.153.0
minimap, v4.13.3
project-manager, v2.5.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by griffin-stewie** [comment]
@boggle 
Can you try to do with latest Atom and asciidoctor-preview package ?
